m3:
	gcc -c -o ./lib/hellomake.o ./src/hellomake.c -I./include
	gcc -c -o ./lib/hellofun.o ./src/hellofun.c -I./include
	gcc -o ./built/hello ./lib/hellomake.o ./lib/hellofun.o -I./include
	./built/hello.exe